### ISSUE TITLE
Need steam protobufs for c#

### ISSUE THREAD

**Issue by RandomNick2** [sometastycake/pysteamauth#15]
Как сделать подобные protobuf message для c#. Ты как то их генерируешь? Я хочу написать подобный проект но на c#

**Comment by sometastycake** [comment]
> Как сделать подобные protobuf message для c#. Ты как то их генерируешь? Я хочу написать подобный проект но на c#

Нужно скомплировать .proto файлы под свой язык
https://protobuf.dev/reference/csharp/csharp-generated/
https://protobuf.dev/getting-started/csharptutorial/#compiling-protocol-buffers

**Comment by RandomNick2** [comment]
Те .proto файлы которые то в readme указал? У меня они как то криво скомпилировались и ошибку выдают
