### ISSUE TITLE
Its not working anymore :(

### ISSUE THREAD

**Issue by SimpleCloudDOTCloud** [sometastycake/pysteamauth#20]
Hey if i run your Extension i got this as an Return Value:

**Fehler bei der Anmeldung: 4 validation errors for FinalizeLoginStatus
steamID
  Field required [type=missing, input_value={'success': False, 'step': 'nonce', 'error': 8}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
redir
  Field required [type=missing, input_value={'success': False, 'step': 'nonce', 'error': 8}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
transfer_info
  Field required [type=missing, input_value={'success': False, 'step': 'nonce', 'error': 8}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
primary_domain
  Field required [type=missing, input_value={'success': False, 'step': 'nonce', 'error': 8}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing**
    
   Looks like a Change in the Steam Backend right?

**Comment by SimpleCloudDOTCloud** [comment]
It looks like the Methode async def _finalize_login returns now:
{"success":false,"step":"nonce","error":8}

**Comment by sometastycake** [comment]
@SimpleCloudDOTCloud 
Error 8 means that invalid parameters were passed
https://steamerrors.com/8
But my code works fine

Can you give an example of the code? And what version of the library are you using?

**Comment by SimpleCloudDOTCloud** [comment]
I'm using v1.1.0 with Python 3.9

The Problem is the Parameter refresh_token
It ist "" or None

If i printed it out, its clear...

My Programm looks like this:
from pysteamauth.auth import Steam
import asyncio

class a ():
        def __init__(self):
                self.steam = Steam(
                login='USERNAME',
                password='PASSWORD',
                )

        async def log_in(self):
                await self.steam.login_to_steam()

b= a()
asyncio.run(b.log_in())

**Comment by sometastycake** [comment]
@SimpleCloudDOTCloud

**Comment by SimpleCloudDOTCloud** [comment]
No it doesnt

**Comment by SimpleCloudDOTCloud** [comment]
_poll_auth_session_status has this return value:
had_remote_interaction: false

**Comment by SimpleCloudDOTCloud** [comment]
> @SimpleCloudDOTCloud
> 
> Does your Steam account have steam guard?

Is it better if it has?

**Comment by sometastycake** [comment]
> Is it better if it has?
It's more about safety.

I tried to log in with an account without Steam Guard, everything was also successful. I'll deal with the problem then

**Comment by sometastycake** [comment]
@SimpleCloudDOTCloud 

Have you previously logged into this account in a browser, and after that from another IP via code?

**Comment by SimpleCloudDOTCloud** [comment]
I Tryed a lot

It looks like that in Line 262 the Value auf the Cookie ist b'xxxxxxxxxxxxxxxxxxxx==
This doenst look right or?

**Comment by sometastycake** [comment]
Because it's base64 encoded protobuf data. You can open up the chrome dev tools in Steam and see that they're sending requests this way. It's not cookies

Can you show me what's inside the auth_session variable? It's defined on line 327.

**Comment by SimpleCloudDOTCloud** [comment]
> @SimpleCloudDOTCloud
> 
> Does your Steam account have steam guard?

client_id: 12009056xxxxxxxxx45
request_id: "]\xxx\xxx-H$\xxxx\xxxw\xxxFf\xxx\xxx\xxx"
interval: 5
allowed_confirmations {
  confirmation_type: k_EAuthSessionGuardType_EmailCode
  associated_message: "simplecloud.cloud"
}
allowed_confirmations {
  confirmation_type: k_EAuthSessionGuardType_MachineToken
}
steamid: 76561199811xxxxxxx
weak_token: "xxxxx"

**Comment by SimpleCloudDOTCloud** [comment]
> > Is it better if it has?
> 
> It's more about safety.
> 
> I tried to log in with an account without Steam Guard, everything was also successful. I'll deal with the problem then

What do i need then to put in Shared Secret 
If i use the Account with Steam Guard i only get a approve Guard, but then the Scripts already crashed

**Comment by SimpleCloudDOTCloud** [comment]
client_id: 123456789
request_id: "\222\111\333\444\261Sm\026\232ID\234\234w\n~"

b'<html><head><title>Bad Request</title></head><body><h1>Bad Request</h1>Please verify that all required parameters are being sent</body></html>'

**Comment by sometastycake** [comment]
```
client_id: 12009056xxxxxxxxx45
request_id: "]\xxx\xxx-H$\xxxx\xxxw\xxxFf\xxx\xxx\xxx"
interval: 5
allowed_confirmations {
  confirmation_type: k_EAuthSessionGuardType_EmailCode
  associated_message: "simplecloud.cloud"
}
allowed_confirmations {
  confirmation_type: k_EAuthSessionGuardType_MachineToken
}
steamid: 76561199811xxxxxxx
weak_token: "xxxxx"``
```

You have the following authentication confirmation types configured
We obviously can't confirm the login by email, it's clear why. I don't know the k_EAuthSessionGuardType_MachineToken method, I need to investigate

Unfortunately, I can't help yet, I'll investigate the problem

**Comment by SimpleCloudDOTCloud** [comment]
I will look after this but thx :)

**Comment by SimpleCloudDOTCloud** [comment]
After setting TTOP it worked :)
Thx Mate for your Late Night help

Also via Steam Chat ;)
